spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: usermanagement
          predicates:
            - Path=/usermanagement/
          uri:  http://localhost:8484
        - id: authentication
          predicates:
            - Path=/auth/login
          uri:  http://localhost:8081
        - id: internal
          predicates:
            - Path=/process/
          uri:  http://localhost:8088
        - id : auth-server
          predicates:
            - Path=/login/
          uri:  http://localhost:8088


  main:
    web-application-type: reactive

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#logging:
#  level:
#    org.springframework.web.HttpLogging: TRACE
#    reactor.netty.http.server: DEBUG
#    reactor.netty.http.client: DEBUG

jwt:
  secret: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b

server:
  port: 8080

authentication:
  enabled: true